// GENERATED by api/tools/gen_data.mjs — do not edit.
export const NAMES = ["Adam Engstrom","Alex Newhook","Alexandre Carrier","Alexandre Texier","Arber Xhekaj","Chris Kreider","Cole Caufield","David Reinbacher","Florian Xhekaj","Ivan Demidov","Jacob Fowler","Jake Evans","Jakub Dobes","Jared Davidson","Jayden Struble","Josh Anderson","Juraj Slafkovský","Kaiden Guhle","Kirby Dach","Lane Hutson","Lucas Condotta","Mike Matheson","Nick Suzuki","Noah Dobson","Oliver Kapanen","Owen Beck","Phillip Danault","Samuel Montembeault","Zachary Bolduc"]
export const NHL_GAMES = [15,338,369,283,230,958,368,2,5,84,17,418,59,10,171,688,282,208,306,166,11,705,537,468,100,28,786,231,175]
export const SCOPES = ["nhl"]
