// GENERATED by api/tools/gen_data.mjs — do not edit.
export const NAMES = ["Adam Engstrom","Alex Newhook","Alexandre Carrier","Alexandre Texier","Arber Xhekaj","Cole Caufield","David Reinbacher","Filip Mesar","Florian Xhekaj","Ivan Demidov","Jacob Fowler","Jake Evans","Jakub Dobes","Jared Davidson","Jayden Struble","Josh Anderson","Juraj Slafkovský","Kaiden Guhle","Kirby Dach","Lane Hutson","Lucas Condotta","Mike Matheson","Nick Suzuki","Noah Dobson","Oliver Kapanen","Owen Beck","Owen Protz","Phillip Danault","Samuel Montembeault","Tyler Thorpe","Zachary Bolduc"]
export const NHL_GAMES = [15,338,369,283,230,368,2,0,5,84,17,418,59,10,171,688,282,208,306,166,11,705,537,468,100,28,0,786,231,0,175]
export const SCOPES = ["nhl"]
