// Regenerates api/src/data.js from the app dataset so the worker can compute
// the daily answer itself. Run after changing players.json.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const src = resolve(here, '../../src/data')

const players = JSON.parse(readFileSync(resolve(src, 'players.json'), 'utf8'))

// Order must match the array the client indexes into, exactly.
const names = players.map(p => p.name)
const nhlGames = players.map(p => p.nhlGames)

const out = `// GENERATED by api/tools/gen_data.mjs — do not edit.
export const NAMES = ${JSON.stringify(names)}
export const NHL_GAMES = ${JSON.stringify(nhlGames)}
export const SCOPES = ["nhl"]
`
writeFileSync(resolve(here, '../src/data.js'), out)
console.log(`wrote ${names.length} players`)
